package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_READ_PO.
 */
public class ChatReadPO {

    private String msgId;
    private long convId;
    private long ctime;
    private String ext;

    public ChatReadPO() {
    }

    public ChatReadPO(String msgId) {
        this.msgId = msgId;
    }

    public ChatReadPO(String msgId, long convId, long ctime, String ext) {
        this.msgId = msgId;
        this.convId = convId;
        this.ctime = ctime;
        this.ext = ext;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public long getConvId() {
        return convId;
    }

    public void setConvId(long convId) {
        this.convId = convId;
    }

    public long getCtime() {
        return ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

}
