package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_MESSAGE_PO.
 */
public class ChatMessagePO {

    private String msgId;
    private long convId;
    private long uid;
    private int direction;
    private Integer type;
    private Integer status;
    private long ctime;
    private String ext;

    public ChatMessagePO() {
    }

    public ChatMessagePO(String msgId) {
        this.msgId = msgId;
    }

    public ChatMessagePO(String msgId, long convId, long uid, int direction, Integer type, Integer status, long ctime, String ext) {
        this.msgId = msgId;
        this.convId = convId;
        this.uid = uid;
        this.direction = direction;
        this.type = type;
        this.status = status;
        this.ctime = ctime;
        this.ext = ext;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public long getConvId() {
        return convId;
    }

    public void setConvId(long convId) {
        this.convId = convId;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public int getDirection() {
        return direction;
    }

    public void setDirection(int direction) {
        this.direction = direction;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public long getCtime() {
        return ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

}
