package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONVERSATION_PO.
 */
public class ConversationPO {

    private Long convId;
    private int type;
    private String lastMessageId;
    private long lastUpdateTime;
    private String lastUpdateMessage;
    private Integer unreadCount;
    private Integer lastUpdateStatus;
    private String convSetting;
    private String ext;

    public ConversationPO() {
    }

    public ConversationPO(Long convId) {
        this.convId = convId;
    }

    public ConversationPO(Long convId, int type, String lastMessageId, long lastUpdateTime, String lastUpdateMessage, Integer unreadCount, Integer lastUpdateStatus, String convSetting, String ext) {
        this.convId = convId;
        this.type = type;
        this.lastMessageId = lastMessageId;
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateMessage = lastUpdateMessage;
        this.unreadCount = unreadCount;
        this.lastUpdateStatus = lastUpdateStatus;
        this.convSetting = convSetting;
        this.ext = ext;
    }

    public Long getConvId() {
        return convId;
    }

    public void setConvId(Long convId) {
        this.convId = convId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getLastMessageId() {
        return lastMessageId;
    }

    public void setLastMessageId(String lastMessageId) {
        this.lastMessageId = lastMessageId;
    }

    public long getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getLastUpdateMessage() {
        return lastUpdateMessage;
    }

    public void setLastUpdateMessage(String lastUpdateMessage) {
        this.lastUpdateMessage = lastUpdateMessage;
    }

    public Integer getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(Integer unreadCount) {
        this.unreadCount = unreadCount;
    }

    public Integer getLastUpdateStatus() {
        return lastUpdateStatus;
    }

    public void setLastUpdateStatus(Integer lastUpdateStatus) {
        this.lastUpdateStatus = lastUpdateStatus;
    }

    public String getConvSetting() {
        return convSetting;
    }

    public void setConvSetting(String convSetting) {
        this.convSetting = convSetting;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

}
