package com.mico.model.po;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mico.model.po.UserProfilePO;
import com.mico.model.po.ConversationPO;
import com.mico.model.po.ChatMessagePO;
import com.mico.model.po.GroupProfilePO;
import com.mico.model.po.SettingPO;
import com.mico.model.po.RelationPO;
import com.mico.model.po.ChatReadPO;
import com.mico.model.po.TranslatePO;

import com.mico.model.po.UserProfilePODao;
import com.mico.model.po.ConversationPODao;
import com.mico.model.po.ChatMessagePODao;
import com.mico.model.po.GroupProfilePODao;
import com.mico.model.po.SettingPODao;
import com.mico.model.po.RelationPODao;
import com.mico.model.po.ChatReadPODao;
import com.mico.model.po.TranslatePODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userProfilePODaoConfig;
    private final DaoConfig conversationPODaoConfig;
    private final DaoConfig chatMessagePODaoConfig;
    private final DaoConfig groupProfilePODaoConfig;
    private final DaoConfig settingPODaoConfig;
    private final DaoConfig relationPODaoConfig;
    private final DaoConfig chatReadPODaoConfig;
    private final DaoConfig translatePODaoConfig;

    private final UserProfilePODao userProfilePODao;
    private final ConversationPODao conversationPODao;
    private final ChatMessagePODao chatMessagePODao;
    private final GroupProfilePODao groupProfilePODao;
    private final SettingPODao settingPODao;
    private final RelationPODao relationPODao;
    private final ChatReadPODao chatReadPODao;
    private final TranslatePODao translatePODao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userProfilePODaoConfig = daoConfigMap.get(UserProfilePODao.class).clone();
        userProfilePODaoConfig.initIdentityScope(type);

        conversationPODaoConfig = daoConfigMap.get(ConversationPODao.class).clone();
        conversationPODaoConfig.initIdentityScope(type);

        chatMessagePODaoConfig = daoConfigMap.get(ChatMessagePODao.class).clone();
        chatMessagePODaoConfig.initIdentityScope(type);

        groupProfilePODaoConfig = daoConfigMap.get(GroupProfilePODao.class).clone();
        groupProfilePODaoConfig.initIdentityScope(type);

        settingPODaoConfig = daoConfigMap.get(SettingPODao.class).clone();
        settingPODaoConfig.initIdentityScope(type);

        relationPODaoConfig = daoConfigMap.get(RelationPODao.class).clone();
        relationPODaoConfig.initIdentityScope(type);

        chatReadPODaoConfig = daoConfigMap.get(ChatReadPODao.class).clone();
        chatReadPODaoConfig.initIdentityScope(type);

        translatePODaoConfig = daoConfigMap.get(TranslatePODao.class).clone();
        translatePODaoConfig.initIdentityScope(type);

        userProfilePODao = new UserProfilePODao(userProfilePODaoConfig, this);
        conversationPODao = new ConversationPODao(conversationPODaoConfig, this);
        chatMessagePODao = new ChatMessagePODao(chatMessagePODaoConfig, this);
        groupProfilePODao = new GroupProfilePODao(groupProfilePODaoConfig, this);
        settingPODao = new SettingPODao(settingPODaoConfig, this);
        relationPODao = new RelationPODao(relationPODaoConfig, this);
        chatReadPODao = new ChatReadPODao(chatReadPODaoConfig, this);
        translatePODao = new TranslatePODao(translatePODaoConfig, this);

        registerDao(UserProfilePO.class, userProfilePODao);
        registerDao(ConversationPO.class, conversationPODao);
        registerDao(ChatMessagePO.class, chatMessagePODao);
        registerDao(GroupProfilePO.class, groupProfilePODao);
        registerDao(SettingPO.class, settingPODao);
        registerDao(RelationPO.class, relationPODao);
        registerDao(ChatReadPO.class, chatReadPODao);
        registerDao(TranslatePO.class, translatePODao);
    }
    
    public void clear() {
        userProfilePODaoConfig.getIdentityScope().clear();
        conversationPODaoConfig.getIdentityScope().clear();
        chatMessagePODaoConfig.getIdentityScope().clear();
        groupProfilePODaoConfig.getIdentityScope().clear();
        settingPODaoConfig.getIdentityScope().clear();
        relationPODaoConfig.getIdentityScope().clear();
        chatReadPODaoConfig.getIdentityScope().clear();
        translatePODaoConfig.getIdentityScope().clear();
    }

    public UserProfilePODao getUserProfilePODao() {
        return userProfilePODao;
    }

    public ConversationPODao getConversationPODao() {
        return conversationPODao;
    }

    public ChatMessagePODao getChatMessagePODao() {
        return chatMessagePODao;
    }

    public GroupProfilePODao getGroupProfilePODao() {
        return groupProfilePODao;
    }

    public SettingPODao getSettingPODao() {
        return settingPODao;
    }

    public RelationPODao getRelationPODao() {
        return relationPODao;
    }

    public ChatReadPODao getChatReadPODao() {
        return chatReadPODao;
    }

    public TranslatePODao getTranslatePODao() {
        return translatePODao;
    }

}
