package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_PROFILE_PO.
 */
public class GroupProfilePO {

    private Long groupId;
    private Integer groupType;
    private Long ownerId;
    private String groupName;
    private String avatar;
    private String description;
    private Integer level;
    private String members;
    private String location;
    private Integer privacy;
    private String extend;
    private Long createTime;

    public GroupProfilePO() {
    }

    public GroupProfilePO(Long groupId) {
        this.groupId = groupId;
    }

    public GroupProfilePO(Long groupId, Integer groupType, Long ownerId, String groupName, String avatar, String description, Integer level, String members, String location, Integer privacy, String extend, Long createTime) {
        this.groupId = groupId;
        this.groupType = groupType;
        this.ownerId = ownerId;
        this.groupName = groupName;
        this.avatar = avatar;
        this.description = description;
        this.level = level;
        this.members = members;
        this.location = location;
        this.privacy = privacy;
        this.extend = extend;
        this.createTime = createTime;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public Integer getGroupType() {
        return groupType;
    }

    public void setGroupType(Integer groupType) {
        this.groupType = groupType;
    }

    public Long getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Integer getPrivacy() {
        return privacy;
    }

    public void setPrivacy(Integer privacy) {
        this.privacy = privacy;
    }

    public String getExtend() {
        return extend;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

}
