package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUSH_DATA_PO.
 */
public class PushDataPO {

    private Long id;
    private Integer type;
    /** Not-null value. */
    private String content;
    private long ctime;
    private String ext;

    public PushDataPO() {
    }

    public PushDataPO(Long id) {
        this.id = id;
    }

    public PushDataPO(Long id, Integer type, String content, long ctime, String ext) {
        this.id = id;
        this.type = type;
        this.content = content;
        this.ctime = ctime;
        this.ext = ext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public long getCtime() {
        return ctime;
    }

    public void setCtime(long ctime) {
        this.ctime = ctime;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

}
