package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RELATION_PO.
 */
public class RelationPO {

    private Long uid;
    private int type;
    private long lastUpdate;

    public RelationPO() {
    }

    public RelationPO(Long uid) {
        this.uid = uid;
    }

    public RelationPO(Long uid, int type, long lastUpdate) {
        this.uid = uid;
        this.type = type;
        this.lastUpdate = lastUpdate;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public long getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(long lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
