package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRANSLATE_PO.
 */
public class TranslatePO {

    private Long id;
    /** Not-null value. */
    private String translateIndex;
    /** Not-null value. */
    private String originText;
    /** Not-null value. */
    private String translateText;
    /** Not-null value. */
    private String locale;
    private Integer type;
    private String ext;

    public TranslatePO() {
    }

    public TranslatePO(Long id) {
        this.id = id;
    }

    public TranslatePO(Long id, String translateIndex, String originText, String translateText, String locale, Integer type, String ext) {
        this.id = id;
        this.translateIndex = translateIndex;
        this.originText = originText;
        this.translateText = translateText;
        this.locale = locale;
        this.type = type;
        this.ext = ext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTranslateIndex() {
        return translateIndex;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTranslateIndex(String translateIndex) {
        this.translateIndex = translateIndex;
    }

    /** Not-null value. */
    public String getOriginText() {
        return originText;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOriginText(String originText) {
        this.originText = originText;
    }

    /** Not-null value. */
    public String getTranslateText() {
        return translateText;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTranslateText(String translateText) {
        this.translateText = translateText;
    }

    /** Not-null value. */
    public String getLocale() {
        return locale;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

}
