package com.mico.model.po;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_PROFILE_PO.
 */
public class UserProfilePO {

    private Long uid;
    private int gendar;
    /** Not-null value. */
    private String displayName;
    private String avatar;
    private String description;
    private Long createTime;
    private Long birthday;
    private Integer level;
    private String extend;

    public UserProfilePO() {
    }

    public UserProfilePO(Long uid) {
        this.uid = uid;
    }

    public UserProfilePO(Long uid, int gendar, String displayName, String avatar, String description, Long createTime, Long birthday, Integer level, String extend) {
        this.uid = uid;
        this.gendar = gendar;
        this.displayName = displayName;
        this.avatar = avatar;
        this.description = description;
        this.createTime = createTime;
        this.birthday = birthday;
        this.level = level;
        this.extend = extend;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public int getGendar() {
        return gendar;
    }

    public void setGendar(int gendar) {
        this.gendar = gendar;
    }

    /** Not-null value. */
    public String getDisplayName() {
        return displayName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getExtend() {
        return extend;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

}
